src/objects/Cast_and_crew__c.object
<CustomObject>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <referenceTo>Title__c</referenceTo>
        <relationshipLabel>Cast and crews</relationshipLabel>
        <relationshipName>Cast_and_crews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cast and crew</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>cast and crew Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cast and crews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Title__c.object
<CustomObject>
    <description>This Object is the master object which has the name, language(lookup), Director, producer,</description>
    <fields>
        <fullName>Cast_and_crew__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cast and crew</label>
        <referenceTo>Cast_and_crew__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Title</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Controller_T.cls
public with sharing class Controller_T {

    public ApexPages.StandardController T1 {get; set;}
    public Title__c Title {get; set;}
    
    public ApexPages.StandardController T2 {get; set;}
    public Cast_And_crew__c Contact {get; set;}
    
        
    public Controller_T(ApexPages.StandardController cntrl) {
        
    }
   /* public pageReference doSaveAll() {
        standardContactController.save();
        T1.save();
        T2.save();
        return null;
    }*/
}