src/objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Title__c.object
<CustomObject>
    <description>This Object is the master object which has the name, language(lookup), Director, producer,</description>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Takes the language as Input</description>
        <inlineHelpText>Enter the language</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Photo__c</fullName>
        <description>Takes the url of the photo</description>
        <label>Photo</label>
        <type>Url</type>
    </fields>
    <label>Title</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TitleCon.cls
public with sharing class TitleCon {

    public TitleCon(ApexPages.StandardSetController controller) {

    }

    public Title__c Title;
    public void TitlePage()
    {
    Title=[select name,language__c,Photo__c from Title__c];
    }
    public title__c getTitle()
    {
    return Title;
    }
    public PageReference save(){
    upsert Title;
    PageReference pref = new ApexPages.standardcontroller(Title).view();
    return pref;
    }
    
}