src/objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Title__c.object
<CustomObject>
    <description>This Object is the master object which has the name, language(lookup), Director, producer,</description>
    <fields>
        <fullName>Language__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Takes the language as Input</description>
        <inlineHelpText>Enter the language</inlineHelpText>
        <label>Language</label>
        <referenceTo>Language__c</referenceTo>
        <relationshipLabel>Titles</relationshipLabel>
        <relationshipName>Titles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Thumbnail__c</fullName>
        <formula>IMAGE(Photo__c, &quot;Photo Unavailable&quot; ,50, 50)</formula>
        <label>MovieImage</label>
        <type>Text</type>
    </fields>
    <label>Title</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/T1.cls
public with sharing class T1{

    public T1() {

    }


    public T1(ApexPages.StandardController controller) {

    }


    public T1(ApexPages.StandardSetController controller) {

    }

List<Title__c> acts = [select Name,Language__c,Thumbnail__c from title__c];
public List<Title__c> getacts(){
return acts;
}
 public PageReference reset() {
    PageReference newpage = new PageReference(System.currentPageReference().getURL());
    newpage.setRedirect(true);
    return newpage;
  }
  public PageReference Language() {
return Page.languages;
}
public PageReference Release() {
return Page.Release;
}
public PageReference CastNCrew() {
return Page.Cast_And_Crew;
}
public PageReference Territories() {
return Page.Territories;
}
public PageReference Title() {
return Page.Page1;
}
}